---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.50.10"}]

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[my_lamp::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
